### ISSUE TITLE
Replay Meteor Method Call From Bookmarks

### ISSUE THREAD

**Issue by renanccastro** [leonardoventurini/meteor-devtools-evolved#1]
Being able to replay a method that is added to the bookmark is a cool addition to the extension is can be extremely helpful while debugging.

**Comment by leonardoventurini** [comment]
Interesting, I will certainly study this further. Thank you.

**Comment by leonardoventurini** [comment]
@renanccastro I added the feature to the development branch, you are welcome to build and test locally if you want. I will release as soon as I have all the features/issues resolved.

**Comment by leonardoventurini** [comment]
Meteor DevTools Evolved v1.1 released including the replay feature. :tada:
