### ISSUE TITLE
Extension context invalidated

### ISSUE THREAD

**Issue by hexsprite** [leonardoventurini/meteor-devtools-evolved#11]
Trying to debug localhost:3000 and getting this error:

![image](https://user-images.githubusercontent.com/23538/84851706-e1f2b880-b00f-11ea-8183-646a91cc1078.png)

**Comment by leonardoventurini** [comment]
That must be something with Chrome... that happens when the background process is updated or removed for some reason and unsynced from the panel process. Does it work after you restart Chrome? @hexsprite
