### ISSUE TITLE
Embedded map blocked

### ISSUE THREAD

**Issue by mhlmhl** [leonardoventurini/meteor-devtools-evolved#12]
A site that I manage, https://bikeloudpdx.org/brainstorm/, shows an embedded map.  It is blocked  by Meteor DevTools Evolved 1.3 running on Chrome Version 83.0.4103.116 (Official Build) (64-bit).  The page works fine when I disable the extension.

bikeloudpdx.org is NOT a Meteor site.  I believe the map is embedded from some GIS system.

**Comment by leonardoventurini** [comment]
Thanks @mhlmhl I will investigate the issue.

**Comment by leonardoventurini** [comment]
@mhlmhl I found the problem, for some reason `error-stack-parser` is polluting global scope and interacting badly with whatever the map is doing. Will try replacing it with another lib.

**Comment by leonardoventurini** [comment]
@mhlmhl I published a new version (1.4) with the fix, anything let me know.
