### ISSUE TITLE
Problem with inject.js

### ISSUE THREAD

**Issue by charlesdeb** [leonardoventurini/meteor-devtools-evolved#17]
When I have your extension enabled in chrome, I get this error on every page:

![image](https://user-images.githubusercontent.com/550014/97093130-5c2bed00-1641-11eb-86b0-fbbf46a8e6a2.png)

I know `inject.js` is not your package - but I just thought I'd let you know. It's not a show stopper - just extra debugging noise in my console.

**Comment by leonardoventurini** [comment]
@charlesdeb does it happen on specific website? can you provide more info?

**Comment by charlesdeb** [comment]
Have a look at the console for this: https://langtrack.net/. Even when I turn off all my extensions (except your one of course) the error shows. However, it doesn't show up in incognito mode in Chrome - so I am not sure what the issue could be...

**Comment by vmusulainen** [comment]
Yes, I have  this issue too.

**Comment by Sylchauf** [comment]
Same here with Brave Browser (v1.17.73 - Chromium v87.0.4280.67) and Meteor 1.11.1

All seems to be functional, it just adds a bit of noise to the console.

**Comment by leonardoventurini** [comment]
thank you, I will be looking into this soon :wink:

**Comment by robinleboe-sw** [comment]
I am also seeing this error. Chrome 87.0.4280.88 and METEOR@1.12

**Comment by wreiske** [comment]
Same. 

chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js
![image](https://user-images.githubusercontent.com/6295044/106518746-9524fa80-6497-11eb-89a3-a1acd627ddf6.png)


![image](https://user-images.githubusercontent.com/6295044/106518599-5ee77b00-6497-11eb-9e91-26e7cd2ded7e.png)

![image](https://user-images.githubusercontent.com/6295044/106518644-70308780-6497-11eb-9bc2-5a041d7345b0.png)

**Comment by jancurn** [comment]
I'm seeing the exact same error in our meteor app...

**Comment by leonardoventurini** [comment]
I figured this one out, the fix will be in the next release.
