### ISSUE TITLE
nothing happens when I click on the icon

### ISSUE THREAD

**Issue by iuvalc** [leonardoventurini/meteor-devtools-evolved#29]
I'm going through the meteor tutorial and I tried installing meteor-devtools-evolved as a Chrome extension. I have MacOS version 10.14.6. Do I need to restart the computer or is it something else?

**Comment by ddaydd** [comment]
Hello,

the extension is in the developer tools

**Comment by iuvalc** [comment]
Thanks!

**Comment by leonardoventurini** [comment]
I will try to make it so the button triggers the devtools in the next release.
