### ISSUE TITLE
Empty Collection Tab on Meteor 2.2

### ISSUE THREAD

**Issue by aboire** [leonardoventurini/meteor-devtools-evolved#35]
Hello with the update for my application in the minimongo tab the collections remains empty, in the old version I saw the data well

**Comment by leonardoventurini** [comment]
@aboire which version of Chrome you are using?

**Comment by leonardoventurini** [comment]
Also, it lists the collections but they are empty?

**Comment by aboire** [comment]
My version of chrome: Version 101.0.4951.64 (Official build) (64 bit).
yes there are the collections but they are empty, I can clearly see the ddp exchanges on the collections and the subscriptions, the performance tab is also empty

**Comment by aboire** [comment]
ok my current version of my project is meteor version 2.2, I did the meteor update test in 2.7.2, and I have the data that is displayed in minimongo, is there a minimum meteor version supported? but still nothing in performance

**Comment by leonardoventurini** [comment]
Interesting, I never had the bandwidth to check different Meteor versions, but I think I can backlog something for the next version. About the performance tab, did you do any interaction with the app which would trigger minimongo methods like `find` or `findOne`?

**Comment by Dartv** [comment]
Same issue on meteor 2.2.
Previous versions of devtools didn't have this problem.

**Comment by leonardoventurini** [comment]
I cannot repro the issue, can you guys share your `packages` and `versions` file?

I tried with the following versions:

![image](https://user-images.githubusercontent.com/17411182/172006247-6b2740df-dd2c-4fe3-92b3-e5417695815e.png)

**Comment by aboire** [comment]
I tested by updating only the packages "meteor update --packages-only" and I have the data in the collections,
I paste here the versions of the packages before I update

```
255kb:meteor-status@1.5.0
aboire:camera-ui@0.0.2
accounts-base@1.9.0
aldeed:autoform@7.0.0
aldeed:collection2@3.2.1
aldeed:schema-deny@3.0.0
aldeed:schema-index@3.0.0
aldeed:template-extension@4.1.0
allow-deny@1.1.0
amplify@1.0.0
autoupdate@1.7.0
babel-compiler@7.6.1
babel-runtime@1.5.0
base64@1.0.12
binary-heap@1.0.11
blaze@2.4.0
blaze-hot@1.0.0
blaze-html-templates@1.2.0
blaze-tools@1.1.1
boilerplate-generator@1.7.1
caching-compiler@1.2.2
caching-html-compiler@1.2.0
callback-hook@1.3.0
check@1.3.1
coffeescript@1.0.17
communecter:account@0.0.5
communecter:deep-link@4.0.4
communecter:mapbox@2.3.1
copleykj:livestamp@1.1.7
cultofcoders:persistent-session@0.4.5
dburles:collection-helpers@1.1.0
ddp@1.4.0
ddp-client@2.4.0
ddp-common@1.4.0
ddp-rate-limiter@1.0.9
ddp-server@2.3.2
deps@1.0.12
diff-sequence@1.1.1
djabatav:geolocation-plus@1.1.9
djabatav:mjml@0.1.5
dynamic-import@0.6.0
ecmascript@0.15.1
ecmascript-runtime@0.7.0
ecmascript-runtime-client@0.11.0
ecmascript-runtime-server@0.10.0
ejson@1.1.1
email@2.0.0
es5-shim@4.8.0
fastclick@1.0.13
fetch@0.1.1
fourseven:scss@4.12.0
froatsnook:valid-email@1.0.0
geojson-utils@1.0.10
hot-code-push@1.0.4
hot-module-replacement@0.2.1
html-tools@1.1.1
htmljs@1.1.0
id-map@1.1.0
inter-process-messaging@0.1.1
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.1.0
iron:router@1.1.2
iron:url@1.1.0
jameslefrere:atjs@0.0.1
jameslefrere:caretjs@0.0.1
jkuester:http@2.0.1
jquery@1.11.11
launch-screen@1.2.1
less@2.8.0
livedata@1.0.18
localstorage@1.2.0
logging@1.2.0
matb33:collection-hooks@1.1.0
mdg:validated-method@1.2.0
meteor@1.9.3
meteorhacks:async@1.0.0
meteorhacks:subs-manager@1.6.4
meteoric:autoform-ionic@0.1.6
meteoric:camera@1.0.3
meteoric:ionic@0.2.0
minifier-css@1.5.3
minifier-js@2.6.0
minimongo@1.6.2
mizzao:timesync@0.5.1
mizzao:user-status@1.0.0
mobile-experience@1.1.0
mobile-status-bar@1.1.0
modern-browsers@0.1.5
modules@0.16.0
modules-runtime@0.12.0
modules-runtime-hot@0.13.0
momentjs:moment@2.29.1
mongo@1.11.0
mongo-decimal@0.1.2
mongo-dev-server@1.1.0
mongo-id@1.0.7
multiply:iron-router-progress@1.0.2
natestrauser:publish-performant-counts@0.1.2
notorii:autoform-datetimepicker@1.0.6
npm-mongo@3.9.0
observe-sequence@1.0.16
ordered-dict@1.1.0
ostrio:logger@2.0.8
ostrio:loggermongo@2.0.5
outatime:geolib@2.0.15
percolate:migrations@1.0.3
promise@0.11.2
quave:reloader@2.0.2
quave:settings@1.0.0
raix:eventemitter@0.1.3
raix:eventstate@0.0.4
raix:handlebar-helpers@0.2.5
raix:push@3.1.0-pre.1
random@1.2.0
rate-limit@1.0.9
react-fast-refresh@0.1.0
reactive-dict@1.3.0
reactive-var@1.0.11
reload@1.3.1
retry@1.1.0
reywood:publish-composite@1.7.3
routepolicy@1.1.0
server-render@0.3.1
service-configuration@1.0.11
session@1.2.0
sha@1.0.9
shell-server@0.5.0
socket-stream-client@0.3.1
spacebars@1.1.0
spacebars-compiler@1.2.1
standard-minifier-css@1.7.2
standard-minifier-js@2.6.0
templating@1.4.0
templating-compiler@1.4.0
templating-runtime@1.4.0
templating-tools@1.2.0
tmeasday:check-npm-versions@0.3.2
tracker@1.2.0
typescript@4.2.2
ui@1.0.13
underscore@1.0.10
universe:i18n@1.20.1
universe:i18n-blaze@1.5.1
url@1.3.1
webapp@1.10.1
webapp-hashing@1.1.0
webtempest:animate@0.1.9
wildhart:jobs@1.0.12
```

**Comment by tdjsnelling** [comment]
I am also having the same problem. Other tabs working as expected, minimongo tab shows list of collections but all are empty. For the time being I have rolled back to v1.4 at `ed4e686290f4deadde66880a1dbc644d4fbbde80` and this is working. My Chrome version is `Version 102.0.5005.61 (Official Build) (x86_64)`.

**Comment by lcampanis** [comment]
Same here. This has been happening for a few months now with MiniMongo having empty collections in latest versions of Chrome & Brave (Mac) in both production and development.
Meteor v2.2.

**Comment by mattandwhatnot** [comment]
I've had the same problem since the update of Meteor DevTools that added the performance tab. 
I'm running Meteor v1.9.3 with Mongo 3.4 (...for annoying production reasons, don't judge me)

**Comment by leonardoventurini** [comment]
Guys, we are having a hard time finding the issue, please try using one of our previous builds in the meantime.

https://github.com/leonardoventurini/meteor-devtools-evolved/tree/development/releases

You can download the `.crx` file and just drag it into Chrome.

Hope it helps, sorry for not thinking of this alternative earlier.

**Comment by SmileHub** [comment]
Downloaded 1.5v., installed to chrome, but the extension is disabled by default even in developers mode and there's no way to enable it :
```
This extension is not listed in the Chrome Web Store and may have been added without your knowledge . [Learn more](https://support.google.com/chrome/?p=ui_remove_non_cws_extensions&hl=en-US)
ID: pmamjjielmkgiegjmkhpafjbgainpkoi 
```
![image](https://user-images.githubusercontent.com/8821939/176657799-6fe0e639-fa85-4f1d-a75e-3b69b27d68dc.png)


If i try to use 1.6v. for my project i get a blank white page when trying to access the extension. If i refresh the extension page, for a short a see a GUI blink and then it's back to white background. While console of plugin "inspect" shows exception: 
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bsubscription%2C%20blockUi%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _i (bundle.js:2:1469106)
    at bundle.js:2:1473927
    at Ra (bundle.js:2:1484913)
    at $l (bundle.js:2:1530752)
    at Lc (bundle.js:2:1516219)
    at Sc (bundle.js:2:1516147)
    at Cc (bundle.js:2:1516010)
    at yc (bundle.js:2:1512997)
    at bundle.js:2:1462784
    at n.unstable_runWithPriority (bundle.js:2:1599359)
```

Other details:
METEOR@2.5.3


Packages:
```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.5.1             # Packages every Meteor app needs to have
mobile-experience@1.1.0       # Packages for a great mobile UX
mongo@1.13.0                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.16.1              # Enable ECMAScript2015+ syntax in app code
typescript@4.4.1              # Enable TypeScript syntax in .ts and .tsx modules
shell-server            # Server-side component of the `meteor shell` command
hot-module-replacement@0.5.0  # Update client in development without reloading the page

react-meteor-data       # React higher-order component for reactively tracking Meteor data
session@1.2.0
accounts-password@2.2.0
alanning:roles
jquery
tracker@1.2.0
fourseven:scss@4.15.0
dynamic-import
underscore@1.0.10
meteorhacks:picker
littledata:synced-cron
dburles:mongo-collection-instances
blaze-html-templates
aldeed:collection2
aldeed:schema-deny
ostrio:files

```
Blank meteor plugin with it's exception screen shot:
![image](https://user-images.githubusercontent.com/8821939/176657022-8f064ebe-e1c7-4572-b88f-013a6d6687a3.png)

Same case with the same project happens on the colleagues machine in another country

![image](https://user-images.githubusercontent.com/8821939/176658387-c7d889c5-a427-4e58-a8d9-b3b48466c707.png)

It must be a special "edge case" because initially on login screen the extension works, only when i try to load a specific project page it crashes (a page that has subscription, it can stopt subscription and resubscribe)

**Comment by salmanhasni** [comment]
having same issue on `meteor 1.10` on `Chrome Version 108.0.5359.124 (Official Build) (64-bit)`

**Comment by salmanhasni** [comment]
@leonardoventurini I have pushed the fix for empty collection, feel free to review it.

**Comment by leonardoventurini** [comment]
Thank you so much @salmanhasni I will merge and test it
