### ISSUE TITLE
Add a way of removing logs that pollute the console on every refresh.

### ISSUE THREAD

**Issue by santiagopuentep** [leonardoventurini/meteor-devtools-evolved#4]
The info logs `Meteor DevTools Evolved: Initializing on the main page...` and `inject.js:2 Meteor DevTools Evolved: Initialized. Attempts: 1.` are always inserted after every refresh. This is polluting the logs and is very annoying, enough for me to have to disable the extension when I'm not going to be using it.

**Comment by leonardoventurini** [comment]
Thanks for the feedback! I had to add those logs to investigate the initialization issue which now seems to be fixed. I will remove those, but it can take up to a week for Chrome to approve the new version.

**Comment by santiagopuentep** [comment]
Great! Thanks for building the tool!

**Comment by leonardoventurini** [comment]
Now the logs will be send to the extension's background sandbox, no more pollution!! :rocket: I will be releasing again at the end of this month.
