### ISSUE TITLE
Uncaught DOMException when using mongo-decimal and a client collection includes a document with a Decimal object.

### ISSUE THREAD

**Issue by gfbeqs** [leonardoventurini/meteor-devtools-evolved#41]
[image](https://user-images.githubusercontent.com/104644085/180332111-273adc82-da1d-43ad-82ac-b677018a78f5.png)

I have a small Meteor project at https://github.com/gfbeqs/mongo-decimal-test that reproduces the issue

```
inject.js:1 Uncaught DOMException: Failed to execute postMessage on Window: function Decimal(v) {
      var e, i, t,
        x = this;

      // Decimal called without new.
      if ...<omitted>... } could not be cloned.
    at e.sendMessage (chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js:1:29403)
    at u (chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js:1:33872)
    at g (chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js:1:24267)
    at m (chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js:1:24542)
    at j (chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js:1:24432)```

**Comment by gunnartorfis** [comment]
Happening to me as well - have to disable the devtools when working with data that contains Decimal128.

**Comment by leonardoventurini** [comment]
Guys, my life has been very crazy at the moment, but now I think I will have some of my bandwidth back and I will certainly check this. Sorry about that.

**Comment by leonardoventurini** [comment]
I implemented a fix, now non-plain objects will be transformed into strings like so:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/17411182/205666144-511bcefa-c5d3-43f2-8dec-0f743c10a695.png">

I will release it until the end of this week.

**Comment by leonardoventurini** [comment]
The fix has been released.
