### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by davidsavoie1** [leonardoventurini/meteor-devtools-evolved#46]
Version 1.8 published three days ago seems to make my application crash with error `Uncaught TypeError: Cannot convert undefined or null to object`. It occurred when publishing a cursor with a nested object of shape `{ location: { coordinates: [...values] } }` if any value in the array was `null`.

I didn't get the error:

- if I deactivated the extension
- if the nested array values returned by the cursor didn't contain `null` values
- if the field containing the array wasn't present in the cursor

I must say that this issue has been very frustrating to track down, as I was trying to identify what in my own code was causing it. I never expected a Chrome extension to actually make my application crash. [This Meteor issue](https://github.com/meteor/meteor/issues/12079) helped me get a hint.

**Comment by leonardoventurini** [comment]
Sorry for your frustration @davidsavoie1, I will investigate the issue.

**Comment by leonardoventurini** [comment]
Fixed the error, will release the extension again in about a week or so.

https://github.com/leonardoventurini/meteor-devtools-evolved/commit/6ae354abc381203bcbb8c9dd8577ea1f2823d8f3#diff-249d8e43d69dcc881c646270a6a787b6b00a5373d76372976ceab556ef490f47R18

**Comment by davidsavoie1** [comment]
Thank you very much. And I'm sorry if my message could be interpreted as harsh, I'm in fact very grateful for your work.

**Comment by leonardoventurini** [comment]
No worries, I completely understand, I could easily find myself in your shoes. Thank you, and thank you for using the extension and providing feedback.

I will also research ways to intercept/wrapping the error messages so users are not misled into thinking a problem is with their code when it is not.

**Comment by leonardoventurini** [comment]
The fix has been released by Chrome, anything let me know.
