### ISSUE TITLE
v1.8.1 crashes browser

### ISSUE THREAD

**Issue by stefanve** [leonardoventurini/meteor-devtools-evolved#48]
I must admit I had forgottten about this extension, but yesterday my site stopped loading in Chrome and some debugging led me to these devtool. It seems that it creates a huge amount of setTimeouts that never happen and warnings keep ackumulating in the console. 
Disabling the tool removed the problems.

**Comment by leonardoventurini** [comment]
Hey @stefanve I am sad to hear this, can you share the warnings here with us? Thank you for reporting it.

**Comment by stefanve** [comment]
Unfortunately Chrome become unresponsive so I cannot check any details, but
what I see is that the "violation" message is repeated and the counter goes
up. It is an old system, probably badly designed, but...
The site is https://www.gesundheitsticket.de and I guess you'd see the same
as I do if you go there. What I know is that the code on the server had not
changed when the problem started.

Thanks,
Stefan

[image: Screenshot from 2023-02-01 16-37-42.png]

**Comment by leonardoventurini** [comment]
Strangely, works fine for me. Which version of chrome are you using? Are you using any other extensions?

Some companies freeze the version of Chrome for some reason.

One thing you can try, if you haven't, is to cycle disable and enable the extension, in the past I think I've seen glitches similar to this.

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/17411182/216110162-142a94c1-fd41-44c2-87b9-f2730928f2fd.png">

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/17411182/216111185-597036e2-c563-4bd5-be11-fa1474366b91.png">

Thanks

**Comment by stefanve** [comment]
You might have a stronger computer than I have, but my Chrome is Version
109.0.5414.119 (Official Build) (64-bit).
I do however think you'd start experiencing problem if you click the
"Suchportal" (green button at top) because it starts to load a huge amount
of data that should not be in a subscription in the first place. So while
the extension should probably not crash - I did help me find an error that
has previously gone unnoticed :)

Thanks
Stefan

**Comment by leonardoventurini** [comment]
Yes, there is an awful lot of data in that page, note at the bottom that it is about 69mb of data downloaded. My suspicion it is related to the images. 

It breaks the minimongo module of the extension, I will research ways to prevent it and warn about the data.

My recommendation is is to use a service to host the images and only have URLs or ids in minimongo, or at least ensure the images are small. It is also loading all partners in Germany (~5k), perhaps there is a way to paginate based on the view box/corner coordinates of the map.

Good luck 💪 If you need any help let me know.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/17411182/216399138-dc12974e-afc5-4a85-a7fd-545540d1e8e4.png">

<img width="841" alt="image" src="https://user-images.githubusercontent.com/17411182/216399604-a269634d-7030-4bed-8cbd-a18bf7f65c8b.png">

**Comment by stefanve** [comment]
OMG! I had completely forgotten that I had allowed them to upload images in there! 
Anyways, there's no reason to have a subscription on that data in the first place. Thank you very much for spending time on something that should not be your problem!

**Comment by leonardoventurini** [comment]
No worries, I'm here to help.
