### ISSUE TITLE
v1.8.1 has no data, v1.6 still does

### ISSUE THREAD

**Issue by kevinkorte** [leonardoventurini/meteor-devtools-evolved#49]
I have a weird issue, I ran updates the other night and now I get 0 data on 1.8.1, but 1.6 still works. 

My system is Ubuntu 20.04.5 LTS
Chrome v109.0.5414.119

My main chrome profile I use for dev work has the 1.8.1 version and has zero data populating it. If I use another chrome profile that still has the 1.6 version all data loads.

I've uninstalled/reinstalled the 1.8.1 version twice, but the same problem persists. I'm not sure what else to try. For now, I'm using my other profile which has the 1.6 version to keep moving forward.

**Comment by leonardoventurini** [comment]
Hey @kevinkorte thanks for reporting it, what version of Meteor are you working on?

**Comment by kevinkorte** [comment]
Hi @leonardoventurini sorry, I was offline a bit. I am on 2.10.0, confirmed tonight I have zero data still.

**Comment by kevinkorte** [comment]
Hey Leonardo, just wanted to give you a quick update, it's now working again. Chrome also updated, I'm now on version 110.0.5481.100.

I'll close this, but I'm also happy to help provide more information if this is something that you want to still investigate further. It's a wonderful tool, though, and I'm so happy it's back.
