### ISSUE TITLE
Noisy warnings on non-Meteor sites

### ISSUE THREAD

**Issue by hexsprite** [leonardoventurini/meteor-devtools-evolved#6]
Hi, thanks for updating this package!

I just wish it wouldn't spam me with messages like this when I am debugging a non-Meteor site:

```
Meteor DevTools Evolved: Initializing from iframe "https://us-u.openx.net/w/1.0/pd?cc=1&plm=10&ph=e6898ebe-7fe9-4fb5-9d9b-8e0fc3013736&gdpr=0"...
chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js:2 Meteor DevTools Evolved: Initializing from iframe "https://us-u.openx.net/w/1.0/pd?cc=1&plm=10&ph=e6898ebe-7fe9-4fb5-9d9b-8e0fc3013736&gdpr=0"...
chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js:2 Meteor DevTools Evolved: Unable to find Meteor on iframe "https://us-u.openx.net/w/1.0/pd?cc=1&plm=10&ph=e6898ebe-7fe9-4fb5-9d9b-8e0fc3013736&gdpr=0"
chrome-extension://ibniinmoafhgbifjojidlagmggecmpgf/build/inject.js:2 Meteor DevTools Evolved: Unable to find Meteor on iframe "https://us-u.openx.net/w/1.0/pd?cc=1&plm=10&ph=e6898ebe-7fe9-4fb5-9d9b-8e0fc3013736&gdpr=0"
```

Depending on the complexity of the site it can fill up the debug buffer making it hard to find real messages.

**Comment by leonardoventurini** [comment]
Yeah I put it there to help the users investigate why the extension would not load anymore, it seems to be fixed now and already removed it in the development branch. I will be releasing in a few days and Chrome takes about a week to review. Sorry about that.

**Comment by leonardoventurini** [comment]
The new version is under review by the Chrome Team as we speak, and it includes a fix for this issue.
