### ISSUE TITLE
Horizontal scrolling required while in sidebar mode

### ISSUE THREAD

**Issue by dmihal** [leonardoventurini/meteor-devtools-evolved#7]
While using devtools docked to the side of the screen, it's not possible to see the full display, and you need to scroll horizontally. The display should be responsive and scale nicely while in sidebar mode.

![image](https://user-images.githubusercontent.com/1661138/79898368-8c1fdc80-83e1-11ea-91e1-7608b8149202.png)

**Comment by leonardoventurini** [comment]
right!? hehe I intend on making a major rework about that soon as time allows it. thank you!
