### ISSUE TITLE
Why not extend Constellation?

### ISSUE THREAD

**Issue by mbatchkarov** [leonardoventurini/meteor-devtools-evolved#9]
Hi, first of all thank you for your work on this project. I've been a happy user of the old Devtools package for a while so updates are appreciated. I especially like the ability to search across all collections.

My question is if you have considered, and if it would make sense, to merge/integrate/collaborate on
 https://github.com/JackAdams/constellation . That package is quite similar in functionality to Meteor devtools and it has a few nice benefits:

- pluggable architecture so people can add extra functionality without having it merged upstream
- a wide selection of plugins, such as Blaze template inspector, autopublish all data, session inspector, editing documents from the client side, etc
- because it is an add-on to your app, it can be used in any browser instead of having to build separate extensions for each browser

It'd be awesome if we could have one package that does everything constellation does, plus the fancy search of meteor devtool

**Comment by leonardoventurini** [comment]
Honestly, I don't know, I have to think about it... I intended this extension to be the most functional possible while being friendly to beginners. I will consider it though, I promise.

I appreciate the suggestion,other ideas might spring from that.
